const router = require('express').Router();

const authRoutes = require('./auth.routes');
const scheduleRoutes = require('./schedule.routes');
const bookingRoutes = require('./booking.routes');
const memberRoutes = require('./member.routes');
const packageRoutes = require('./package.routes');
const coachRoutes = require('./coach.routes');
const coachSalaryRoutes = require('./coach-salary.routes');
const storeRoutes = require('./store.routes');
const holidayRoutes = require('./holiday.routes');
const danceStyleRoutes = require('./danceStyle.routes');
const bannerRoutes = require('./banner.routes');
const configRoutes = require('./config.routes');
const accountRoutes = require('./account.routes');
const logRoutes = require('./log.routes');
const uploadRoutes = require('./upload.routes');
const statsRoutes = require('./stats.routes');
const homeRoutes = require('./home.routes');
const weekTemplateRoutes = require('./week-template.routes');
const qrcodeRoutes = require('./qrcode.routes');
const systemRoutes = require('./system.routes');
const attendanceRoutes = require('./attendance.routes');
const transferRoutes = require('./transfer.routes');
const imageRoutes = require('./image.routes');

router.use('/auth', authRoutes);
router.use('/schedules', scheduleRoutes);
router.use('/bookings', bookingRoutes);
router.use('/members', memberRoutes);
router.use('/packages', packageRoutes);
router.use('/package-activations', packageRoutes);
router.use('/package-extensions', packageRoutes);
router.use('/coaches', coachRoutes);
router.use('/coach-salaries', coachSalaryRoutes);
router.use('/stores', storeRoutes);
router.use('/holidays', holidayRoutes);
router.use('/announces', require('./announcement.routes'));
router.use('/dance-styles', danceStyleRoutes);
router.use('/banners', bannerRoutes);
router.use('/config', configRoutes);
router.use('/accounts', accountRoutes);
router.use('/logs', logRoutes);
router.use('/upload', uploadRoutes);
router.use('/stats', statsRoutes);
router.use('/home', homeRoutes);
router.use('/week-template', weekTemplateRoutes);
router.use('/qrcode', qrcodeRoutes);
router.use('/system', systemRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/transfers', transferRoutes);
router.use('/template-mappings', require('./template-mapping.routes'));
router.use('/images', imageRoutes);

module.exports = router;
