"use strict";

/* This file is automatically generated and should not be manually edited. */
/* To modify this file, please run the `npm run build` command instead. */

0 && (module.exports = {
    /* @Annotate_start: the CommonJS named exports for ESM import in node */
    _apply_decorated_descriptor: null,
    _apply_decs_2203_r: null,
    _apply_decs_2311: null,
    _array_like_to_array: null,
    _array_with_holes: null,
    _array_without_holes: null,
    _assert_this_initialized: null,
    _async_generator: null,
    _async_generator_delegate: null,
    _async_iterator: null,
    _async_to_generator: null,
    _await_async_generator: null,
    _await_value: null,
    _call_super: null,
    _check_private_redeclaration: null,
    _class_apply_descriptor_destructure: null,
    _class_apply_descriptor_get: null,
    _class_apply_descriptor_set: null,
    _class_apply_descriptor_update: null,
    _class_call_check: null,
    _class_check_private_static_access: null,
    _class_check_private_static_field_descriptor: null,
    _class_extract_field_descriptor: null,
    _class_name_tdz_error: null,
    _class_private_field_destructure: null,
    _class_private_field_get: null,
    _class_private_field_init: null,
    _class_private_field_loose_base: null,
    _class_private_field_loose_key: null,
    _class_private_field_set: null,
    _class_private_field_update: null,
    _class_private_method_get: null,
    _class_private_method_init: null,
    _class_private_method_set: null,
    _class_static_private_field_destructure: null,
    _class_static_private_field_spec_get: null,
    _class_static_private_field_spec_set: null,
    _class_static_private_field_update: null,
    _class_static_private_method_get: null,
    _construct: null,
    _create_class: null,
    _create_for_of_iterator_helper_loose: null,
    _create_super: null,
    _decorate: null,
    _defaults: null,
    _define_enumerable_properties: null,
    _define_property: null,
    _dispose: null,
    _export_star: null,
    _extends: null,
    _get: null,
    _get_prototype_of: null,
    _identity: null,
    _inherits: null,
    _inherits_loose: null,
    _initializer_define_property: null,
    _initializer_warning_helper: null,
    _instanceof: null,
    _interop_require_default: null,
    _interop_require_wildcard: null,
    _is_native_function: null,
    _is_native_reflect_construct: null,
    _iterable_to_array: null,
    _iterable_to_array_limit: null,
    _iterable_to_array_limit_loose: null,
    _jsx: null,
    _new_arrow_check: null,
    _non_iterable_rest: null,
    _non_iterable_spread: null,
    _object_destructuring_empty: null,
    _object_spread: null,
    _object_spread_props: null,
    _object_without_properties: null,
    _object_without_properties_loose: null,
    _overload_yield: null,
    _possible_constructor_return: null,
    _read_only_error: null,
    _set: null,
    _set_prototype_of: null,
    _skip_first_generator_next: null,
    _sliced_to_array: null,
    _sliced_to_array_loose: null,
    _super_prop_base: null,
    _tagged_template_literal: null,
    _tagged_template_literal_loose: null,
    _throw: null,
    _to_array: null,
    _to_consumable_array: null,
    _to_primitive: null,
    _to_property_key: null,
    _ts_add_disposable_resource: null,
    _ts_decorate: null,
    _ts_dispose_resources: null,
    _ts_generator: null,
    _ts_metadata: null,
    _ts_param: null,
    _ts_rewrite_relative_import_extension: null,
    _ts_values: null,
    _type_of: null,
    _unsupported_iterable_to_array: null,
    _update: null,
    _using: null,
    _using_ctx: null,
    _wrap_async_generator: null,
    _wrap_native_super: null,
    _wrap_reg_exp: null,
    _write_only_error: null
    /* @Annotate_end */
});
module.exports = {
    get _apply_decorated_descriptor() {
        return require("./_apply_decorated_descriptor.js")._;
    },
    get _apply_decs_2203_r() {
        return require("./_apply_decs_2203_r.js")._;
    },
    get _apply_decs_2311() {
        return require("./_apply_decs_2311.js")._;
    },
    get _array_like_to_array() {
        return require("./_array_like_to_array.js")._;
    },
    get _array_with_holes() {
        return require("./_array_with_holes.js")._;
    },
    get _array_without_holes() {
        return require("./_array_without_holes.js")._;
    },
    get _assert_this_initialized() {
        return require("./_assert_this_initialized.js")._;
    },
    get _async_generator() {
        return require("./_async_generator.js")._;
    },
    get _async_generator_delegate() {
        return require("./_async_generator_delegate.js")._;
    },
    get _async_iterator() {
        return require("./_async_iterator.js")._;
    },
    get _async_to_generator() {
        return require("./_async_to_generator.js")._;
    },
    get _await_async_generator() {
        return require("./_await_async_generator.js")._;
    },
    get _await_value() {
        return require("./_await_value.js")._;
    },
    get _call_super() {
        return require("./_call_super.js")._;
    },
    get _check_private_redeclaration() {
        return require("./_check_private_redeclaration.js")._;
    },
    get _class_apply_descriptor_destructure() {
        return require("./_class_apply_descriptor_destructure.js")._;
    },
    get _class_apply_descriptor_get() {
        return require("./_class_apply_descriptor_get.js")._;
    },
    get _class_apply_descriptor_set() {
        return require("./_class_apply_descriptor_set.js")._;
    },
    get _class_apply_descriptor_update() {
        return require("./_class_apply_descriptor_update.js")._;
    },
    get _class_call_check() {
        return require("./_class_call_check.js")._;
    },
    get _class_check_private_static_access() {
        return require("./_class_check_private_static_access.js")._;
    },
    get _class_check_private_static_field_descriptor() {
        return require("./_class_check_private_static_field_descriptor.js")._;
    },
    get _class_extract_field_descriptor() {
        return require("./_class_extract_field_descriptor.js")._;
    },
    get _class_name_tdz_error() {
        return require("./_class_name_tdz_error.js")._;
    },
    get _class_private_field_destructure() {
        return require("./_class_private_field_destructure.js")._;
    },
    get _class_private_field_get() {
        return require("./_class_private_field_get.js")._;
    },
    get _class_private_field_init() {
        return require("./_class_private_field_init.js")._;
    },
    get _class_private_field_loose_base() {
        return require("./_class_private_field_loose_base.js")._;
    },
    get _class_private_field_loose_key() {
        return require("./_class_private_field_loose_key.js")._;
    },
    get _class_private_field_set() {
        return require("./_class_private_field_set.js")._;
    },
    get _class_private_field_update() {
        return require("./_class_private_field_update.js")._;
    },
    get _class_private_method_get() {
        return require("./_class_private_method_get.js")._;
    },
    get _class_private_method_init() {
        return require("./_class_private_method_init.js")._;
    },
    get _class_private_method_set() {
        return require("./_class_private_method_set.js")._;
    },
    get _class_static_private_field_destructure() {
        return require("./_class_static_private_field_destructure.js")._;
    },
    get _class_static_private_field_spec_get() {
        return require("./_class_static_private_field_spec_get.js")._;
    },
    get _class_static_private_field_spec_set() {
        return require("./_class_static_private_field_spec_set.js")._;
    },
    get _class_static_private_field_update() {
        return require("./_class_static_private_field_update.js")._;
    },
    get _class_static_private_method_get() {
        return require("./_class_static_private_method_get.js")._;
    },
    get _construct() {
        return require("./_construct.js")._;
    },
    get _create_class() {
        return require("./_create_class.js")._;
    },
    get _create_for_of_iterator_helper_loose() {
        return require("./_create_for_of_iterator_helper_loose.js")._;
    },
    get _create_super() {
        return require("./_create_super.js")._;
    },
    get _decorate() {
        return require("./_decorate.js")._;
    },
    get _defaults() {
        return require("./_defaults.js")._;
    },
    get _define_enumerable_properties() {
        return require("./_define_enumerable_properties.js")._;
    },
    get _define_property() {
        return require("./_define_property.js")._;
    },
    get _dispose() {
        return require("./_dispose.js")._;
    },
    get _export_star() {
        return require("./_export_star.js")._;
    },
    get _extends() {
        return require("./_extends.js")._;
    },
    get _get() {
        return require("./_get.js")._;
    },
    get _get_prototype_of() {
        return require("./_get_prototype_of.js")._;
    },
    get _identity() {
        return require("./_identity.js")._;
    },
    get _inherits() {
        return require("./_inherits.js")._;
    },
    get _inherits_loose() {
        return require("./_inherits_loose.js")._;
    },
    get _initializer_define_property() {
        return require("./_initializer_define_property.js")._;
    },
    get _initializer_warning_helper() {
        return require("./_initializer_warning_helper.js")._;
    },
    get _instanceof() {
        return require("./_instanceof.js")._;
    },
    get _interop_require_default() {
        return require("./_interop_require_default.js")._;
    },
    get _interop_require_wildcard() {
        return require("./_interop_require_wildcard.js")._;
    },
    get _is_native_function() {
        return require("./_is_native_function.js")._;
    },
    get _is_native_reflect_construct() {
        return require("./_is_native_reflect_construct.js")._;
    },
    get _iterable_to_array() {
        return require("./_iterable_to_array.js")._;
    },
    get _iterable_to_array_limit() {
        return require("./_iterable_to_array_limit.js")._;
    },
    get _iterable_to_array_limit_loose() {
        return require("./_iterable_to_array_limit_loose.js")._;
    },
    get _jsx() {
        return require("./_jsx.js")._;
    },
    get _new_arrow_check() {
        return require("./_new_arrow_check.js")._;
    },
    get _non_iterable_rest() {
        return require("./_non_iterable_rest.js")._;
    },
    get _non_iterable_spread() {
        return require("./_non_iterable_spread.js")._;
    },
    get _object_destructuring_empty() {
        return require("./_object_destructuring_empty.js")._;
    },
    get _object_spread() {
        return require("./_object_spread.js")._;
    },
    get _object_spread_props() {
        return require("./_object_spread_props.js")._;
    },
    get _object_without_properties() {
        return require("./_object_without_properties.js")._;
    },
    get _object_without_properties_loose() {
        return require("./_object_without_properties_loose.js")._;
    },
    get _overload_yield() {
        return require("./_overload_yield.js")._;
    },
    get _possible_constructor_return() {
        return require("./_possible_constructor_return.js")._;
    },
    get _read_only_error() {
        return require("./_read_only_error.js")._;
    },
    get _set() {
        return require("./_set.js")._;
    },
    get _set_prototype_of() {
        return require("./_set_prototype_of.js")._;
    },
    get _skip_first_generator_next() {
        return require("./_skip_first_generator_next.js")._;
    },
    get _sliced_to_array() {
        return require("./_sliced_to_array.js")._;
    },
    get _sliced_to_array_loose() {
        return require("./_sliced_to_array_loose.js")._;
    },
    get _super_prop_base() {
        return require("./_super_prop_base.js")._;
    },
    get _tagged_template_literal() {
        return require("./_tagged_template_literal.js")._;
    },
    get _tagged_template_literal_loose() {
        return require("./_tagged_template_literal_loose.js")._;
    },
    get _throw() {
        return require("./_throw.js")._;
    },
    get _to_array() {
        return require("./_to_array.js")._;
    },
    get _to_consumable_array() {
        return require("./_to_consumable_array.js")._;
    },
    get _to_primitive() {
        return require("./_to_primitive.js")._;
    },
    get _to_property_key() {
        return require("./_to_property_key.js")._;
    },
    get _ts_add_disposable_resource() {
        return require("./_ts_add_disposable_resource.js")._;
    },
    get _ts_decorate() {
        return require("./_ts_decorate.js")._;
    },
    get _ts_dispose_resources() {
        return require("./_ts_dispose_resources.js")._;
    },
    get _ts_generator() {
        return require("./_ts_generator.js")._;
    },
    get _ts_metadata() {
        return require("./_ts_metadata.js")._;
    },
    get _ts_param() {
        return require("./_ts_param.js")._;
    },
    get _ts_rewrite_relative_import_extension() {
        return require("./_ts_rewrite_relative_import_extension.js")._;
    },
    get _ts_values() {
        return require("./_ts_values.js")._;
    },
    get _type_of() {
        return require("./_type_of.js")._;
    },
    get _unsupported_iterable_to_array() {
        return require("./_unsupported_iterable_to_array.js")._;
    },
    get _update() {
        return require("./_update.js")._;
    },
    get _using() {
        return require("./_using.js")._;
    },
    get _using_ctx() {
        return require("./_using_ctx.js")._;
    },
    get _wrap_async_generator() {
        return require("./_wrap_async_generator.js")._;
    },
    get _wrap_native_super() {
        return require("./_wrap_native_super.js")._;
    },
    get _wrap_reg_exp() {
        return require("./_wrap_reg_exp.js")._;
    },
    get _write_only_error() {
        return require("./_write_only_error.js")._;
    }
};

// ===== swc-runtime compat（由 gen-swc-runtime.js 追加）=====
(function () {
  try {
    var keys = Object.keys(module.exports);
    var main = null;
    for (var i = 0; i < keys.length; i++) {
      if (typeof module.exports[keys[i]] === 'function') { main = module.exports[keys[i]]; break; }
    }
    if (typeof main !== 'function' || typeof module.exports === 'function') return;
    
    main._ = main;
    main.default = main;
    module.exports = main;
  } catch (e) { /* 保持原导出 */ }
})();
